### PR TITLE
Update 1.json

### PR DESCRIPTION
**Pull request by nonamepool**
man this is my new pool please accept , i need to mine this coin.
this is my email ( ahmedpopstar0@gmail.com ) please mail me if rejected with the reason of rejection

### CODE REVIEW

**Comment by nonamepool** [comment]
man why no review or even comment.
man answer me i need to work on my pool.
please contact me ASAP.

**Comment by nonamepool** [comment]
@mtwaro

**Comment by nonamepool** [comment]
@mtwaro  why no answer

**Comment by mtwaro** [comment]
@nonamepool Hi, sorry for the late reply. Mining BTCV requires a DDMS license. The code you've submitted will not provide you one, it will only show your pool's label on the explorer. Please contact WDMO for the latest information regarding the licensing. 

For now I close the PR, but if your pool receives the license, it will surely be shown on the explorer.

**Comment by nonamepool** [comment]
How to get this licence

**Pull request closed without merging**
